### ISSUE TITLE
Can't use 443 HTTPS proxy port anymore

### ISSUE THREAD

**Issue by berpergian** [Frizz925/gbf-proxy#9]
I have been experiencing this problem for more than two months, if i use 8088 proxy port the game load slowly

The ISP i use is Indihome

**Comment by frizz925** [comment]
What's the actual cause of the problem? The only problem it has right now is certificate expiration but that happens very recently because I haven't renewed my SSL certificate.

**Comment by berpergian** [comment]
I always use your gbf-proxy with HTTPS port 443 but it's been more than a month that I can't access the game in that way

So now I am using HTTP port 8088 but it is very slow to load the game, can I use the previous way? (maybe my problem has been mentioned by you about SSL certificate)

**Comment by frizz925** [comment]
If the previous way you meant is the HTTPS port 443 then you can try it again, I just renewed the certificate recently.

For the problem with accessing the game through the HTTPS port (outside of expired certificate), I'm not sure what's causing it because I couldn't replicate your problem. Have you checked if this also happens on other ISPs as well?

**Comment by berpergian** [comment]
Ah thank you, that's solved my problem.

Hmm, sorry I've never tried it with other ISP since I only know that Indihome has problem with GBF
